@startuml ClassDiagram

class CurrentWorkDay {
    TimeStamp startTime
    TimeStamp endTime
    double pauseDuration
    void StartShift()
    void EndShift()
}
class ConsoleUI{
   CurrentWorkDay workDay
   Stopwatch stopwatch
    
}

@enduml